"""Software-only Virtual PAT Controller.

This module provides proportional orientation correction for the virtual camera,
steering the camera optical axis towards detected beacon centroids based strictly
on AlignmentResult perception metrics.
"""

from dataclasses import dataclass
from typing import Dict, Any
from src.detection.alignment import AlignmentResult


@dataclass
class ControllerResult:
    """Encapsulates output angle adjustments generated by the PAT controller.
    
    Attributes:
        delta_orientation_deg (float): Angular orientation adjustment step in degrees.
        new_orientation_deg (float): Resulting camera pointing orientation in degrees.
        active (bool): True if a non-zero pointing correction was applied.
    """
    delta_orientation_deg: float
    new_orientation_deg: float
    active: bool

    def to_dict(self) -> Dict[str, Any]:
        """Returns controller result metrics as a dictionary."""
        return {
            "delta_orientation_deg": self.delta_orientation_deg,
            "new_orientation_deg": self.new_orientation_deg,
            "active": self.active,
        }


class VirtualPATController:
    """Proportional Virtual PAT Controller.
    
    Attributes:
        kp (float): Proportional gain coefficient (degree adjustment per degree error).
        max_step_deg (float): Maximum allowed angular step per update frame (slew rate limit).
        enabled (bool): Global operational switch for automated orientation corrections.
    """

    def __init__(
        self,
        kp: float = 0.15,
        max_step_deg: float = 1.0,
        enabled: bool = True
    ) -> None:
        self.kp = float(kp)
        self.max_step_deg = float(max_step_deg)
        self.enabled = bool(enabled)

    def update(
        self,
        current_orientation_deg: float,
        alignment_res: AlignmentResult
    ) -> ControllerResult:
        """Computes orientation correction step from pointing alignment results.
        
        Args:
            current_orientation_deg (float): Current camera orientation in degrees.
            alignment_res (AlignmentResult): Boresight alignment metrics from perception.
            
        Returns:
            ControllerResult: Angular adjustment step, new target orientation, and active flag.
        """
        # If disabled or alignment state is not MISALIGNED, no correction is applied
        if (
            not self.enabled
            or not alignment_res.detected
            or alignment_res.alignment_state != "MISALIGNED"
            or alignment_res.angular_error_deg is None
        ):
            return ControllerResult(
                delta_orientation_deg=0.0,
                new_orientation_deg=float(current_orientation_deg),
                active=False
            )

        # 1. Calculate proportional angular correction delta
        raw_delta = self.kp * alignment_res.angular_error_deg

        # 2. Clamp correction delta within max step rate limit [-max_step_deg, +max_step_deg]
        clamped_delta = float(max(-self.max_step_deg, min(self.max_step_deg, raw_delta)))

        # 3. Determine if a non-zero correction step was applied
        is_active = abs(clamped_delta) > 1e-6
        final_delta = clamped_delta if is_active else 0.0

        new_orientation = float(current_orientation_deg + final_delta)

        return ControllerResult(
            delta_orientation_deg=final_delta,
            new_orientation_deg=new_orientation,
            active=is_active
        )
